import React, { useState, useEffect } from 'react';
import { Home, List, Map, AlertTriangle, Settings, Bell, TrendingUp, Radio, Maximize, AlertCircle, ChevronDown, Check, Download, Users, ChevronRight, BarChart, Search, Filter, MapPin, Loader2, LogOut } from 'lucide-react';
import { chartData } from '../mockData'; // keep chartData static for now as backend has no history chart endpoint
import { getDashboardInfo, getAllReports, updateReportStatus } from '../api/admin';
import { useAuth } from '../context/AuthContext';
import { MapContainer, TileLayer, Marker, Popup } from 'react-leaflet';
import 'leaflet/dist/leaflet.css';
import L from 'leaflet';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

import icon from 'leaflet/dist/images/marker-icon.png';
import iconRetina from 'leaflet/dist/images/marker-icon-2x.png';
import iconShadow from 'leaflet/dist/images/marker-shadow.png';

delete L.Icon.Default.prototype._getIconUrl;
L.Icon.Default.mergeOptions({
  iconRetinaUrl: iconRetina,
  iconUrl: icon,
  shadowUrl: iconShadow,
});

export default function AdminView() {
  const { user, logout } = useAuth();
  const [searchQuery, setSearchQuery] = useState('');
  const [statusFilter, setStatusFilter] = useState('all');
  const [activeTab, setActiveTab] = useState('overview');
  
  const [kpiData, setKpiData] = useState(null);
  const [reports, setReports] = useState([]);
  const [loading, setLoading] = useState(true);
  const [updating, setUpdating] = useState(null); // id of report being updated
  const [selectedReport, setSelectedReport] = useState(null); // specific report details modal
  
  const [alertLevel, setAlertLevel] = useState('red');
  const [targetZone, setTargetZone] = useState('all');

  // Modals state
  const [newUnitModal, setNewUnitModal] = useState(false);
  const [newUnitForm, setNewUnitForm] = useState({ name: '', type: 'General Assignment', personnel: 2 });
  const [assignModal, setAssignModal] = useState({ open: false, teamId: null, teamName: null });

  const [fieldTeams, setFieldTeams] = useState([
    { id: 1, name: 'Unit Alpha', type: 'Heavy Duty Pump Truck', zone: 'Adyar Zone', status: 'Dispatched', personnel: 4, lastActive: '2 mins ago', ticketId: null },
    { id: 2, name: 'Rescue-Boat 3', type: 'Coastal Patrol', zone: 'Marina Beach', status: 'Available', personnel: 2, lastActive: 'Live', ticketId: null },
    { id: 3, name: 'Civic Team 7', type: 'Debris Clearance', zone: 'Tambaram', status: 'Available', personnel: 6, lastActive: '1 hr ago', ticketId: null },
    { id: 4, name: 'Med-Evac 1', type: 'Emergency Response', zone: 'Central Chennai', status: 'Offline', personnel: 3, lastActive: '5 hrs ago', ticketId: null },
    { id: 5, name: 'Unit Delta', type: 'Sewer Maintenance', zone: 'Ennore', status: 'Dispatched', personnel: 5, lastActive: '15 mins ago', ticketId: null }
  ]);

  const submitNewUnit = () => {
    if (newUnitForm.name.trim() === '') return;
    setFieldTeams([
      { id: Date.now(), name: newUnitForm.name, type: newUnitForm.type, zone: 'Headquarters', status: 'Available', personnel: newUnitForm.personnel, lastActive: 'Just now', ticketId: null },
      ...fieldTeams
    ]);
    setNewUnitModal(false);
    setNewUnitForm({ name: '', type: 'General Assignment', personnel: 2 });
  };

  const submitReassign = (ticketId, zoneName) => {
    // 1. Update the team assignment
    setFieldTeams(prev => prev.map(t => t.id === assignModal.teamId ? { ...t, zone: zoneName, status: 'Dispatched', lastActive: 'Live', ticketId } : t));
    
    // 2. Update the ticket to show assigned team + auto-set status to assigned
    setReports(prev => prev.map(r => r.id === ticketId ? { ...r, assignedTeamId: assignModal.teamId, status: 'assigned' } : r));
    
    // 3. Sync status to backend
    updateReportStatus(ticketId, 'assigned', null).catch(e => console.error('Failed to sync assignment status', e));
    
    setAssignModal({ open: false, teamId: null, teamName: null });
  };

  const handleExportPDF = () => {
    if (!reports || reports.length === 0) {
      alert("No data available to export.");
      return;
    }

    const doc = new jsPDF();
    
    // Header
    doc.setFontSize(22);
    doc.setTextColor(30, 58, 138); // blue-900
    doc.text("FlowGuard: Civic Issue Report", 14, 22);
    
    doc.setFontSize(11);
    doc.setTextColor(100);
    doc.text(`Generated by: Command Center on ${new Date().toLocaleString()}`, 14, 30);
    
    // Summary
    const resolved = reports.filter(r => r.status === 'resolved').length;
    const highSev = reports.filter(r => r.severity === 'high').length;
    doc.setFontSize(10);
    doc.text(`Total Tickets: ${reports.length} | Resolved: ${resolved} | High Priority: ${highSev}`, 14, 38);

    doc.setLineWidth(0.5);
    doc.line(14, 42, 196, 42);

    // Table
    const tableColumn = ["Ticket ID", "Category", "Status", "Severity", "Reporter", "Date"];
    const tableRows = [];

    reports.forEach(r => {
      tableRows.push([
        r.id.substring(0, 8),
        r.category?.replace('_', ' ')?.toUpperCase() || 'N/A',
        r.status?.toUpperCase(),
        r.severity?.toUpperCase() || 'LOW',
        r.profiles?.full_name || 'Anonymous',
        new Date(r.created_at).toLocaleDateString()
      ]);
    });

    autoTable(doc, {
      head: [tableColumn],
      body: tableRows,
      startY: 48,
      theme: 'grid',
      headStyles: { fillColor: [37, 99, 235] },
      alternateRowStyles: { fillColor: [248, 250, 252] },
      styles: { fontSize: 9, cellPadding: 3 },
      columnStyles: {
        0: { fontStyle: 'bold' },
        3: { fontStyle: 'bold' }
      },
      didParseCell: function(data) {
        // Red color for HIGH severity cells in the severity column (index 3)
        if (data.section === 'body' && data.column.index === 3 && data.cell.raw === 'HIGH') {
          data.cell.styles.textColor = [220, 38, 38];
        }
      }
    });

    doc.save(`FlowGuard_Report_${new Date().toISOString().split('T')[0]}.pdf`);
  };

  const handleBroadcast = () => {
    alert(`Successfully dispatched ${alertLevel.toUpperCase()} alert to targeted zones (${targetZone.toUpperCase()}) via SMS and Push Notification Network!`);
  };

  useEffect(() => {
    fetchData();
    const interval = setInterval(fetchData, 30000); // Polling every 30s
    return () => clearInterval(interval);
  }, []);

  const fetchData = async () => {
    try {
      const [dashRes, repRes] = await Promise.all([
        getDashboardInfo(),
        getAllReports(1, 50)
      ]);
      setKpiData(dashRes.data);
      
      // Preserve local team assignments across backend refreshes
      setReports(prev => {
        const assignmentMap = {};
        prev.forEach(r => { if (r.assignedTeamId) assignmentMap[r.id] = r.assignedTeamId; });
        return (repRes.data || []).map(r => ({
          ...r,
          assignedTeamId: assignmentMap[r.id] || r.assignedTeamId || null
        }));
      });
    } catch (e) {
      console.error("Failed to fetch admin data", e);
    } finally {
      if (loading) setLoading(false);
    }
  };

  const handleStatusChange = async (id, newStatus) => {
    setUpdating(id);
    try {
      await updateReportStatus(id, newStatus, null);
      
      // If resolved, free the assigned team
      if (newStatus === 'resolved') {
        const ticket = reports.find(r => r.id === id);
        if (ticket?.assignedTeamId) {
          setFieldTeams(prev => prev.map(t => t.id === ticket.assignedTeamId ? { ...t, status: 'Available', zone: 'Headquarters', lastActive: 'Just now', ticketId: null } : t));
        }
      }
      
      // If assigned manually (without team), just sync
      if (newStatus === 'assigned') {
        setReports(prev => prev.map(r => r.id === id ? { ...r, status: 'assigned' } : r));
      }
      
      fetchData();
    } catch (e) {
      console.error("Failed to update status", e);
      alert("Failed to update: " + (e.response?.data?.error || e.message));
    } finally {
      setUpdating(null);
    }
  };

  if (loading) {
    return (
      <div className="w-full min-h-screen subtle-bg flex items-center justify-center relative">
         <Loader2 className="animate-spin h-10 w-10 text-blue-600" />
      </div>
    );
  }

  return (
    <div className="w-full min-h-screen subtle-bg flex overflow-hidden relative">

      {/* Sidebar - Clean Light Theme */}
      <div className="w-64 bg-white border-r border-gray-200 flex flex-col z-10 shadow-sm relative">
        <div className="p-6 border-b border-gray-100 flex items-center">
           <div className="w-8 h-8 bg-blue-600 rounded-lg flex items-center justify-center mr-3 text-white shadow-sm"><AlertCircle size={20}/></div>
           <h1 className="font-display font-bold text-xl tracking-tight text-gray-900">
             FlowGuard <span className="text-blue-600 text-[10px] uppercase tracking-widest align-top ml-1">Gov</span>
           </h1>
        </div>
        
        <div className="p-4 flex flex-col h-full justify-between">
          <nav className="space-y-1">
            {[
              { id: 'overview', icon: Home, label: 'Overview' },
              { id: 'analytics', icon: BarChart, label: 'Analytics' },
              { id: 'reports', icon: List, label: 'Ticket Queue' },
              { id: 'map', icon: Map, label: 'Live Heatmap' },
              { id: 'broadcasts', icon: Radio, label: 'E-Broadcasts' },
              { id: 'teams', icon: Users, label: 'Field Teams' },
            ].map((item, i) => (
              <button 
                 key={item.id} 
                 onClick={() => setActiveTab(item.id)}
                 className={`w-full flex items-center space-x-3 px-4 py-3 rounded-xl transition-all font-medium text-sm ${activeTab === item.id ? 'bg-blue-50 text-blue-700' : 'text-gray-600 hover:bg-gray-50 hover:text-gray-900'}`}
              >
                <item.icon size={18} className={activeTab === item.id ? 'text-blue-600' : 'text-gray-400'}/>
                <span>{item.label}</span>
              </button>
            ))}
          </nav>

          <div className="mt-auto space-y-2 pt-6 border-t border-gray-100">
            <button className="w-full flex items-center space-x-3 px-4 py-3 rounded-xl transition-all font-medium text-sm text-gray-600 hover:bg-gray-50">
              <Settings size={18} className="text-gray-400"/>
              <span>System Settings</span>
            </button>
            <div className="flex items-center space-x-3 p-3 bg-gray-50 rounded-xl border border-gray-100 mt-4 relative group cursor-pointer" onClick={logout}>
              <div className="w-9 h-9 rounded-full bg-blue-100 text-blue-700 flex items-center justify-center font-bold text-sm border border-blue-200">CO</div>
              <div className="flex-1 overflow-hidden">
                <p className="text-sm font-bold text-gray-900 truncate">{user?.full_name}</p>
                <p className="text-[10px] text-gray-500 font-medium truncate">Chief Officer</p>
              </div>
              <LogOut size={16} className="text-gray-400 opacity-0 group-hover:opacity-100 transition-opacity absolute right-4" />
            </div>
          </div>
        </div>
      </div>

      {/* Main Content */}
      <div className="flex-1 flex flex-col z-10 w-full overflow-hidden">
        {/* Top bar */}
        <header className="h-16 bg-white border-b border-gray-200 flex justify-between items-center px-8 shadow-sm shrink-0">
          <div className="flex items-center">
            <h2 className="font-display font-semibold text-gray-800">Command Center <span className="text-gray-400 font-normal mx-2">/</span> Overview</h2>
          </div>
          <div className="flex items-center space-x-6">
            <span className="text-sm text-gray-500 font-medium bg-gray-100 px-3 py-1 rounded-full">{new Date().toLocaleDateString('en-GB')} • {new Date().toLocaleTimeString('en-GB', {hour: '2-digit', minute:'2-digit'})}</span>
            <button className="relative p-2 text-gray-400 hover:text-gray-600 transition-colors">
              <Bell size={20} />
              <span className="absolute top-1 right-1 w-2.5 h-2.5 bg-red-500 rounded-full border-2 border-white"></span>
            </button>
          </div>
        </header>

        {/* Dashboard Content */}
        <div className="flex-1 p-8 overflow-y-auto space-y-6 custom-scrollbar">
          
          <div className="flex justify-between items-end">
             <div>
                <h2 className="font-display text-2xl font-bold text-gray-900 capitalize">
                   {activeTab === 'overview' ? 'City Overview' : activeTab.replace('-', ' ')}
                </h2>
                <p className="text-gray-500 text-sm mt-1">Real-time metrics for Chennai Metropolitan Area.</p>
             </div>
             <button onClick={handleExportPDF} className="bg-white border border-gray-200 text-gray-700 font-semibold px-4 py-2 rounded-lg text-sm hover:bg-gray-50 flex items-center shadow-sm transition-colors active:scale-95">
               <Download size={16} className="mr-2" /> Export Report
             </button>
          </div>

          {/* OVERVIEW / ANALYTICS Tabs */}
          {(activeTab === 'overview' || activeTab === 'analytics') && (
            <div className="grid grid-cols-5 gap-4">
              <div className="modern-card p-5 relative overflow-hidden bg-white border-l-4 border-l-blue-500">
                <p className="text-gray-500 text-xs font-semibold uppercase tracking-wider mb-2">Total Reports</p>
                <div className="flex items-end justify-between">
                  <span className="text-3xl font-display font-bold text-gray-900">{kpiData?.total_reports || 0}</span>
                  <span className="text-amber-500 flex items-center text-xs font-bold bg-amber-50 px-2 py-0.5 rounded"><TrendingUp size={14} className="mr-1"/> Live</span>
                </div>
              </div>
              <div className="modern-card p-5 relative overflow-hidden bg-white border-l-4 border-l-red-500">
                <div className="absolute top-4 right-4"><div className="w-2.5 h-2.5 bg-red-500 rounded-full animate-pulse shadow-[0_0_8px_#EF4444]"></div></div>
                <p className="text-gray-500 text-xs font-semibold uppercase tracking-wider mb-2">Code Red Zones</p>
                <span className="text-3xl font-display font-bold text-red-600">{kpiData?.code_red_zones?.length || 0}</span>
              </div>
              <div className="modern-card p-5 relative overflow-hidden bg-white border-l-4 border-l-green-500">
                <p className="text-gray-500 text-xs font-semibold uppercase tracking-wider mb-2">Resolved Today</p>
                <span className="text-3xl font-display font-bold text-green-600">{kpiData?.reports_by_status?.resolved || 0}</span>
              </div>
              <div className="modern-card p-5 relative overflow-hidden bg-white border-l-4 border-l-amber-500">
                <p className="text-gray-500 text-xs font-semibold uppercase tracking-wider mb-2">Active SOS</p>
                <span className="text-3xl font-display font-bold text-amber-600">{kpiData?.active_sos || 0}</span>
              </div>
              <div className="modern-card p-5 relative overflow-hidden bg-white border-l-4 border-l-purple-500 shadow-sm">
                <p className="text-gray-500 text-xs font-semibold uppercase tracking-wider mb-2">Resolution Rate</p>
                <div className="flex items-center space-x-2">
                   <span className="text-3xl font-display font-bold text-gray-900">
                     {kpiData?.total_reports ? Math.round(((kpiData?.reports_by_status?.resolved || 0) / kpiData.total_reports) * 100) : 0}%
                   </span>
                </div>
              </div>
            </div>
          )}

          {/* GRAPHS & MAPS: Shown in Overview, Analytics, Map */}
          {(activeTab === 'overview' || activeTab === 'analytics' || activeTab === 'map') && (
            <div className="grid grid-cols-1 xl:grid-cols-3 gap-6">
              
              {/* Resolution Trends Graph Placeholder */}
              {(activeTab === 'overview' || activeTab === 'analytics') && (
                <div className="modern-card bg-white p-6 xl:col-span-2 flex flex-col min-h-[350px]">
                   <div className="flex justify-between items-center mb-6">
                     <h3 className="font-semibold text-gray-900 border-b-2 border-transparent">Volume Trends (7 Days)</h3>
                     <div className="flex items-center space-x-4 text-sm">
                       <div className="flex items-center text-gray-500"><span className="w-3 h-3 bg-blue-500 rounded-sm mr-2"></span> New Tickets</div>
                       <div className="flex items-center text-gray-500"><span className="w-3 h-3 bg-green-500 rounded-sm mr-2"></span> Resolved</div>
                     </div>
                   </div>
                   
                   <div className="flex-1 flex items-end justify-between space-x-2 pt-4 relative">
                      <div className="absolute left-0 top-0 bottom-8 border-r border-gray-100 pr-2 flex flex-col justify-between text-xs text-gray-400">
                        <span>100</span><span>75</span><span>50</span><span>25</span><span>0</span>
                      </div>
                      <div className="pl-8 flex w-full justify-between items-end h-full">
                        {chartData.map((d, i) => (
                          <div key={i} className="flex flex-col items-center flex-1 mx-2 group">
                            <div className="w-full flex space-x-1 items-end pt-10 h-[220px]">
                               <div className="w-1/2 bg-blue-500 rounded-t-sm hover:bg-blue-600 transition-colors" style={{height: `${d.new}%`}}></div>
                               <div className="w-1/2 bg-green-500 rounded-t-sm hover:bg-green-600 transition-colors" style={{height: `${d.resolved}%`}}></div>
                            </div>
                            <span className="text-xs text-gray-500 mt-3 font-medium">{d.day}</span>
                          </div>
                        ))}
                      </div>
                   </div>
                </div>
              )}

              {/* Quick Map Widget: Shown in Map tab or Overview */}
              {(activeTab === 'overview' || activeTab === 'map') && (
                <div className={`modern-card bg-white border flex flex-col relative overflow-hidden ${activeTab === 'map' ? 'col-span-5 min-h-[75vh]' : 'xl:col-span-1 min-h-[350px]'}`}>
                  <div className="p-4 border-b border-gray-100 flex justify-between items-center bg-white z-10 hover:bg-gray-50 transition-colors" onClick={() => setActiveTab('map')}>
                    <h3 className="font-semibold text-gray-900 cursor-pointer">Live Density Map</h3>
                    <button className="text-gray-400 hover:text-gray-600 bg-gray-50 p-1.5 rounded-lg border border-gray-200"><Maximize size={16}/></button>
                  </div>
                  <div className="flex-1 relative bg-slate-100 flex items-center justify-center -m-[1px] z-0">
                    <MapContainer 
                      key={`map-view-${activeTab}`}
                      center={[13.0827, 80.2707]} 
                      zoom={11} 
                      className={`w-full h-full ${activeTab === 'map' ? 'min-h-[75vh]' : 'min-h-[350px]'}`}
                    >
                      <TileLayer
                        attribution='&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'
                        url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
                      />
                      {reports.map((r) => r.latitude && r.longitude ? (
                        <Marker key={r.id} position={[Number(r.latitude), Number(r.longitude)]}>
                          <Popup>
                            <div className="font-sans p-1">
                              <h4 className="font-bold text-gray-900 capitalize">{r.category?.replace('_', ' ')}</h4>
                              <p className="text-sm font-semibold mt-1 capitalize text-blue-600">{r.status}</p>
                              <p className="text-xs text-gray-500 mt-1">{new Date(r.created_at).toLocaleDateString()}</p>
                            </div>
                          </Popup>
                        </Marker>
                      ) : null)}
                    </MapContainer>
                  </div>
                </div>
              )}
            </div>
          )}

          {/* BROADCASTS Tab */}
          {(activeTab === 'overview' || activeTab === 'broadcasts') && (
            <div className={`modern-card border p-6 flex flex-col items-center justify-between gap-6 transition-colors ${alertLevel === 'red' ? 'border-red-200 bg-red-50' : alertLevel === 'orange' ? 'border-orange-200 bg-orange-50' : alertLevel === 'yellow' ? 'border-amber-200 bg-amber-50' : 'border-green-200 bg-green-50'}`}>
               <div className="w-full relative">
                 <h3 className={`font-display font-bold text-lg flex items-center ${alertLevel === 'red' ? 'text-red-900' : alertLevel === 'orange' ? 'text-orange-900' : alertLevel === 'yellow' ? 'text-amber-900' : 'text-green-900'}`}>
                   <Radio size={20} className={`mr-2 ${alertLevel === 'red' ? 'text-red-600 animate-pulse' : alertLevel === 'orange' ? 'text-orange-600' : alertLevel === 'yellow' ? 'text-amber-500' : 'text-green-600'}`}/> 
                   Emergency Broadcast System
                 </h3>
                 <p className={`text-sm mt-1 ${alertLevel === 'red' ? 'text-red-700' : alertLevel === 'orange' ? 'text-orange-700' : alertLevel === 'yellow' ? 'text-amber-700' : 'text-green-700'}`}>
                   Configure and issue mass SMS and app push notifications to targeted civil geofences.
                 </p>
               </div>
               
               <div className="flex flex-col md:flex-row w-full gap-4 items-end bg-white p-4 rounded-xl shadow-sm border border-gray-100">
                 
                 <div className="flex-1 w-full">
                    <label className="text-xs font-bold text-gray-500 uppercase tracking-wider mb-1.5 block">Alert Level</label>
                    <select 
                      value={alertLevel}
                      onChange={(e) => setAlertLevel(e.target.value)}
                      className="w-full bg-gray-50 border border-gray-200 text-gray-900 rounded-lg px-4 py-2.5 text-sm font-semibold focus:ring-2 focus:ring-blue-500 focus:outline-none cursor-pointer"
                    >
                      <option value="red">🔴 CODE RED (Critical Danger)</option>
                      <option value="orange">🟠 CODE ORANGE (High Risk)</option>
                      <option value="yellow">🟡 CODE YELLOW (Be Prepared)</option>
                      <option value="green">🟢 CODE GREEN (All Clear / Safe)</option>
                    </select>
                 </div>

                 <div className="flex-1 w-full">
                    <label className="text-xs font-bold text-gray-500 uppercase tracking-wider mb-1.5 block">Target Demographics / Zones</label>
                    <select 
                      value={targetZone}
                      onChange={(e) => setTargetZone(e.target.value)}
                      className="w-full bg-gray-50 border border-gray-200 text-gray-900 rounded-lg px-4 py-2.5 text-sm font-medium focus:ring-2 focus:ring-blue-500 focus:outline-none cursor-pointer"
                    >
                      <option value="all">Global: All Coastal Zones & Citizens</option>
                      <option value="marina">Local: Marina & Santhome District</option>
                      <option value="ennore">Local: Ennore Industrial Zone</option>
                      <option value="besant">Local: Besant Nagar & Thiruvanmiyur</option>
                      <option value="fishermen">Targeted: Registered Fishermen Only</option>
                    </select>
                 </div>

                 <button 
                   onClick={handleBroadcast}
                   className={`text-white font-bold px-8 py-2.5 rounded-lg transition-transform active:scale-95 shadow-sm whitespace-nowrap h-[42px] ${alertLevel === 'red' ? 'bg-red-600 hover:bg-red-700 shadow-red-200' : alertLevel === 'orange' ? 'bg-orange-500 hover:bg-orange-600 shadow-orange-200' : alertLevel === 'yellow' ? 'bg-amber-500 hover:bg-amber-600 shadow-amber-200' : 'bg-green-600 hover:bg-green-700 shadow-green-200'}`}
                 >
                   Dispatch Broadcast
                 </button>
               </div>
            </div>
          )}

          {/* TEAMS Tab */}
          {activeTab === 'teams' && (
             <div className="space-y-6">
               <div className="modern-card bg-white p-5 border-b border-gray-100 flex justify-between items-center">
                 <div>
                   <h3 className="font-display font-bold text-gray-900 text-lg flex items-center"><Users size={20} className="mr-2 text-blue-600"/> Active Field Units</h3>
                   <p className="text-sm text-gray-500 mt-1">Manage physical deployment teams and infrastructure repair vehicles.</p>
                 </div>
                 <button onClick={() => setNewUnitModal(true)} className="bg-blue-600 hover:bg-blue-700 text-white font-bold px-4 py-2 rounded-lg text-sm transition-colors shadow-sm cursor-pointer">
                   + New Unit
                 </button>
               </div>
               
               <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                 {fieldTeams.map((team) => (
                   <div key={team.id} className="modern-card bg-white border border-gray-200 overflow-hidden hover:shadow-md transition-shadow">
                     <div className="p-4 border-b border-gray-100 flex justify-between items-start">
                       <div>
                         <h4 className="font-bold text-gray-900 leading-tight">{team.name}</h4>
                         <p className="text-xs font-semibold text-gray-500 uppercase tracking-wide mt-1">{team.type}</p>
                       </div>
                       <span className={`inline-flex items-center px-2.5 py-0.5 rounded-md text-xs font-bold border ${
                         team.status === 'Available' ? 'bg-green-50 text-green-700 border-green-200' :
                         team.status === 'Dispatched' ? 'bg-amber-50 text-amber-700 border-amber-200 animate-pulse' :
                         'bg-gray-100 text-gray-600 border-gray-200'
                       }`}>
                         {team.status}
                       </span>
                     </div>
                     <div className="p-4 bg-gray-50 text-sm space-y-2">
                       <div className="flex justify-between items-center text-gray-700">
                         <span className="flex items-center"><MapPin size={14} className="mr-1.5 text-gray-400"/> Deployed To</span>
                         <span className="font-semibold text-gray-900 text-right max-w-[180px] truncate" title={team.zone}>{team.zone}</span>
                       </div>
                       {team.ticketId && (() => {
                         const ticket = reports.find(r => r.id === team.ticketId);
                         return ticket ? (
                           <div className="flex justify-between items-center text-gray-700">
                             <span className="flex items-center"><AlertCircle size={14} className="mr-1.5 text-gray-400"/> Linked Ticket</span>
                             <span className="font-semibold text-blue-700 text-xs">#{ticket.id.substring(0,6)} · {ticket.category?.replace('_',' ')}</span>
                           </div>
                         ) : null;
                       })()}
                       {team.ticketId && (() => {
                         const ticket = reports.find(r => r.id === team.ticketId);
                         return ticket ? (
                           <a href={`https://www.google.com/maps?q=${ticket.latitude},${ticket.longitude}`} target="_blank" rel="noreferrer" className="flex items-center text-xs text-blue-600 hover:underline mt-1">
                             <Map size={12} className="mr-1"/> Open in Google Maps
                           </a>
                         ) : null;
                       })()}
                       <div className="flex justify-between items-center text-gray-700">
                         <span className="flex items-center"><Users size={14} className="mr-1.5 text-gray-400"/> Active Personnel</span>
                         <span className="font-semibold text-gray-900">{team.personnel} Operatives</span>
                       </div>
                     </div>
                     <div className="p-3 bg-white border-t border-gray-100 flex justify-between items-center">
                        <span className="text-xs font-medium text-gray-400">Last Ping: {team.lastActive}</span>
                        <button onClick={() => setAssignModal({ open: true, teamId: team.id, teamName: team.name })} className="text-blue-600 text-sm font-bold hover:underline cursor-pointer">Re-assign</button>
                     </div>
                   </div>
                 ))}
               </div>
             </div>
          )}

          {/* QUEUE Tab / TICKET QUEUE */}
          {(activeTab === 'overview' || activeTab === 'reports') && (
            <div className="modern-card bg-white flex flex-col overflow-hidden">
              <div className="p-5 border-b border-gray-200 flex justify-between items-center bg-white">
                <h3 className="font-display font-bold text-gray-900 flex items-center"><AlertCircle size={18} className="mr-2 text-blue-600"/> Ticket Queue <span className="ml-2 bg-blue-100 text-blue-700 px-2 py-0.5 rounded text-xs">{reports.length} Total</span></h3>
                <div className="flex items-center space-x-3">
                  <select 
                    value={statusFilter} 
                    onChange={e => setStatusFilter(e.target.value)}
                    className="bg-gray-50 border border-gray-200 text-gray-900 rounded-lg px-3 py-2 text-sm font-medium focus:ring-2 focus:ring-blue-500 focus:outline-none cursor-pointer"
                  >
                    <option value="all">All Status</option>
                    <option value="reported">🔵 Reported</option>
                    <option value="assigned">🟠 Assigned</option>
                    <option value="resolved">🟢 Resolved</option>
                  </select>
                  <div className="relative">
                    <Search size={16} className="absolute left-3 top-2.5 text-gray-400" />
                    <input type="text" placeholder="Search ID or Keyword..." value={searchQuery} onChange={e => setSearchQuery(e.target.value)} className="pl-9 pr-4 py-2 border border-gray-200 rounded-lg text-sm focus:ring-2 focus:ring-blue-500 focus:outline-none w-64 bg-gray-50"/>
                  </div>
                </div>
              </div>
              <div className="overflow-x-auto">
                <table className="w-full text-left border-collapse">
                  <thead>
                    <tr className="bg-gray-50 border-b border-gray-200">
                      <th className="p-4 text-xs font-semibold text-gray-500 uppercase">Ticket ID</th>
                      <th className="p-4 text-xs font-semibold text-gray-500 uppercase">Issue & Reporter</th>
                      <th className="p-4 text-xs font-semibold text-gray-500 uppercase">AI Tag</th>
                      <th className="p-4 text-xs font-semibold text-gray-500 uppercase">Assigned Unit</th>
                      <th className="p-4 text-xs font-semibold text-gray-500 uppercase">Severity</th>
                      <th className="p-4 text-xs font-semibold text-gray-500 uppercase">Status</th>
                      <th className="p-4 text-xs font-semibold text-gray-500 uppercase text-right">Action</th>
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-gray-100">
                    {reports.length === 0 ? (
                      <tr><td colSpan="7" className="p-8 text-center text-gray-500">No reports found.</td></tr>
                    ) : reports
                      .filter(r => statusFilter === 'all' || r.status === statusFilter)
                      .filter(r => r.category.toLowerCase().includes(searchQuery.toLowerCase()) || r.id.includes(searchQuery))
                      .map(r => (
                      <tr key={r.id} className="hover:bg-gray-50 transition-colors group">
                        <td className="p-4 font-mono text-sm text-gray-900 font-medium">{r.id.substring(0,8)}...</td>
                        <td className="p-4">
                          <div className="text-sm font-bold text-gray-900 capitalize">{r.category?.replace('_', ' ')}</div>
                          <div className="text-xs text-gray-500 mt-1">{r.profiles?.full_name || 'Citizen'} • {new Date(r.created_at).toLocaleDateString()}</div>
                          {r.location_name && <div className="text-xs text-blue-600 mt-0.5 truncate max-w-[200px]" title={r.location_name}><MapPin size={10} className="inline mr-0.5"/>{r.location_name}</div>}
                        </td>
                        <td className="p-4">
                          <span className="inline-flex items-center px-2.5 py-0.5 rounded-md text-xs font-medium bg-blue-50 text-blue-700 border border-blue-100">
                            {r.blockage_type || 'General'}
                          </span>
                        </td>
                        <td className="p-4">
                          {r.assignedTeamId ? (
                             <span className="inline-flex items-center text-xs font-bold text-blue-800 bg-blue-100 px-2 py-0.5 rounded border border-blue-200 shadow-sm whitespace-nowrap"><Users size={12} className="mr-1"/> {fieldTeams.find(t => t.id === r.assignedTeamId)?.name || 'Unit'}</span>
                          ) : (
                             <span className="text-xs font-medium text-gray-400 italic">Unassigned</span>
                          )}
                        </td>
                        <td className="p-4">
                          <span className={`inline-flex items-center px-2.5 py-1 rounded-full text-xs font-bold border ${r.severity === 'high' ? 'bg-red-50 text-red-700 border-red-200' : r.severity === 'medium' ? 'bg-amber-50 text-amber-700 border-amber-200' : 'bg-green-50 text-green-700 border-green-200'}`}>
                            {r.severity?.toUpperCase() || 'LOW'}
                          </span>
                        </td>
                        <td className="p-4">
                          <select 
                            value={r.status} 
                            onChange={(e) => handleStatusChange(r.id, e.target.value)}
                            disabled={updating === r.id}
                            className="text-xs font-medium p-1 border border-gray-200 rounded outline-none"
                          >
                            <option value="reported">Reported</option>
                            <option value="assigned">Assigned</option>
                            <option value="resolved">Resolved</option>
                          </select>
                          {updating === r.id && <Loader2 size={12} className="inline ml-2 animate-spin text-blue-500" />}
                        </td>
                        <td className="p-4 text-right">
                          <button onClick={() => setSelectedReport(r)} className="text-sm font-medium text-blue-600 hover:text-blue-800 hover:underline cursor-pointer">View Detail <ChevronRight size={14} className="inline align-middle"/></button>
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </div>
          )}

        </div>
      {/* Assign Unit Modal */}
      {assignModal.open && (
        <div className="fixed inset-0 bg-black/50 z-50 flex items-center justify-center p-4 backdrop-blur-sm animate-in fade-in duration-200">
          <div className="bg-white rounded-2xl w-full max-w-md overflow-hidden shadow-2xl flex flex-col">
            <div className="p-4 border-b border-gray-100 flex justify-between items-center bg-gray-50">
              <h3 className="font-bold text-gray-900 flex items-center"><MapPin size={18} className="mr-2 text-blue-600"/> Dispatch {assignModal.teamName}</h3>
              <button onClick={() => setAssignModal({open: false, teamId: null, teamName: null})} className="text-gray-500 hover:text-gray-800 font-medium">Close</button>
            </div>
            <div className="p-6 space-y-4">
               <div>
                 <label className="text-xs font-bold text-gray-500 uppercase tracking-wider mb-2 block">Select Active Civic Ticket</label>
                 <select 
                    id="ticketSelect"
                    className="w-full bg-gray-50 border border-gray-200 text-gray-900 rounded-lg px-4 py-3 text-sm font-medium focus:ring-2 focus:ring-blue-500 focus:outline-none cursor-pointer"
                 >
                    <option value="">-- Choose Ticket Destination --</option>
                    {reports.filter(r => r.status !== 'resolved').map(r => (
                      <option key={r.id} value={JSON.stringify({id: r.id, location: r.location_name || `Lat ${Number(r.latitude).toFixed(3)}, Lng ${Number(r.longitude).toFixed(3)}`})}>
                        #{r.id.substring(0,6)} · {r.category?.replace('_', ' ')} — {r.location_name || `${Number(r.latitude).toFixed(3)}°N, ${Number(r.longitude).toFixed(3)}°E`}
                      </option>
                    ))}
                 </select>
               </div>
               <button 
                 onClick={() => {
                   const sel = document.getElementById('ticketSelect').value;
                   if (!sel) return alert("Please select a ticket destination.");
                   const data = JSON.parse(sel);
                   submitReassign(data.id, data.location);
                 }}
                 className="w-full bg-blue-600 hover:bg-blue-700 text-white font-bold py-3 rounded-xl transition-colors shadow-sm cursor-pointer"
               >
                 Confirm Dispatch
               </button>
            </div>
          </div>
        </div>
      )}

      {/* New Unit Modal */}
      {newUnitModal && (
        <div className="fixed inset-0 bg-black/50 z-50 flex items-center justify-center p-4 backdrop-blur-sm animate-in fade-in duration-200">
          <div className="bg-white rounded-2xl w-full max-w-md overflow-hidden shadow-2xl flex flex-col">
            <div className="p-4 border-b border-gray-100 flex justify-between items-center bg-gray-50">
              <h3 className="font-bold text-gray-900 flex items-center"><Users size={18} className="mr-2 text-blue-600"/> Create New Unit</h3>
              <button onClick={() => setNewUnitModal(false)} className="text-gray-500 hover:text-gray-800 font-medium">Close</button>
            </div>
            <div className="p-6 space-y-4">
               <div>
                  <label className="text-xs font-bold text-gray-500 uppercase tracking-wider mb-2 block">Unit Designation Name</label>
                  <input type="text" value={newUnitForm.name} onChange={e => setNewUnitForm({...newUnitForm, name: e.target.value})} placeholder="e.g. Unit Echo, Rescue 9" className="w-full bg-gray-50 border border-gray-200 text-gray-900 rounded-lg px-4 py-2.5 text-sm font-medium focus:ring-2 focus:ring-blue-500 focus:outline-none"/>
               </div>
               <div className="grid grid-cols-2 gap-4">
                 <div>
                    <label className="text-xs font-bold text-gray-500 uppercase tracking-wider mb-2 block">Unit Type</label>
                    <select value={newUnitForm.type} onChange={e => setNewUnitForm({...newUnitForm, type: e.target.value})} className="w-full bg-gray-50 border border-gray-200 text-gray-900 rounded-lg px-4 py-2.5 text-sm font-medium focus:ring-2 focus:ring-blue-500 focus:outline-none cursor-pointer">
                      <option value="General Assignment">General Assignment</option>
                      <option value="Heavy Duty Pump Truck">Heavy Duty Pump Truck</option>
                      <option value="Coastal Patrol">Coastal Patrol</option>
                      <option value="Debris Clearance">Debris Clearance</option>
                      <option value="Medical Evac">Medical Evac</option>
                    </select>
                 </div>
                 <div>
                    <label className="text-xs font-bold text-gray-500 uppercase tracking-wider mb-2 block">Personnel Count</label>
                    <input type="number" min="1" max="20" value={newUnitForm.personnel} onChange={e => setNewUnitForm({...newUnitForm, personnel: parseInt(e.target.value)})} className="w-full bg-gray-50 border border-gray-200 text-gray-900 rounded-lg px-4 py-2.5 text-sm font-medium focus:ring-2 focus:ring-blue-500 focus:outline-none"/>
                 </div>
               </div>
               <button onClick={submitNewUnit} className="w-full bg-blue-600 hover:bg-blue-700 text-white font-bold py-3 mt-4 rounded-xl transition-colors shadow-sm cursor-pointer">
                 Activate Unit
               </button>
            </div>
          </div>
        </div>
      )}

      {selectedReport && (
        <div className="fixed inset-0 bg-black/50 z-50 flex items-center justify-center p-4 backdrop-blur-sm animate-in fade-in duration-200">
          <div className="bg-white rounded-2xl w-full max-w-3xl overflow-hidden shadow-2xl flex flex-col max-h-[90vh]">
            <div className="p-4 border-b border-gray-100 flex justify-between items-center bg-gray-50">
              <h3 className="font-bold text-gray-900 text-lg">Ticket Detail: #{selectedReport.id.substring(0,8)}</h3>
              <button onClick={() => setSelectedReport(null)} className="text-gray-500 hover:text-gray-800 font-medium">Close</button>
            </div>
            <div className="p-6 overflow-y-auto flex-1 grid grid-cols-1 md:grid-cols-2 gap-6 custom-scrollbar">
               <div>
                  <h4 className="text-sm font-semibold text-gray-400 uppercase tracking-widest mb-1">Issue Overview</h4>
                  <p className="text-xl font-bold text-gray-900 capitalize mb-4">{selectedReport.category?.replace('_', ' ')}</p>
                  
                  <div className="space-y-4">
                    <div className="bg-gray-50 p-3 rounded-lg border border-gray-100">
                      <p className="text-xs text-gray-500 font-semibold mb-1">Reporter Information</p>
                      <p className="text-sm font-bold text-gray-900">{selectedReport.profiles?.full_name || 'Anonymous Citizen'}</p>
                      <p className="text-xs text-gray-500">{selectedReport.profiles?.phone_number || 'No phone provided'}</p>
                    </div>
                    
                    <div className="bg-gray-50 p-3 rounded-lg border border-gray-100">
                      <p className="text-xs text-gray-500 font-semibold mb-1">Location Details</p>
                      {selectedReport.location_name && (
                        <p className="text-sm font-bold text-gray-900 mb-1"><MapPin size={14} className="inline mr-1 text-blue-500"/>{selectedReport.location_name}</p>
                      )}
                      <p className="text-sm font-medium text-gray-700"><MapPin size={14} className="inline mr-1 text-gray-400"/>Lat: {Number(selectedReport.latitude).toFixed(4)}, Lng: {Number(selectedReport.longitude).toFixed(4)}</p>
                      <a 
                        href={`https://www.google.com/maps?q=${selectedReport.latitude},${selectedReport.longitude}`}
                        target="_blank" rel="noreferrer"
                        className="inline-flex items-center mt-2 text-xs font-bold text-blue-600 bg-blue-50 px-3 py-1.5 rounded-lg border border-blue-100 hover:bg-blue-100 transition-colors"
                      >
                        <Map size={12} className="mr-1.5"/> Open in Google Maps
                      </a>
                      <p className="text-xs text-gray-500 mt-2">Reported on {new Date(selectedReport.created_at).toLocaleString()}</p>
                    </div>

                    <div className="bg-gray-50 p-3 rounded-lg border border-gray-100">
                      <p className="text-xs text-gray-500 font-semibold mb-1">Ticket Details</p>
                      <p className="text-sm font-bold text-gray-900 capitalize">Status: <span className={selectedReport.status === 'resolved' ? 'text-green-600' : selectedReport.status === 'assigned' ? 'text-amber-600' : 'text-blue-600'}>{selectedReport.status}</span></p>
                      <p className={`text-sm font-bold capitalize mt-1 ${selectedReport.severity === 'high' ? 'text-red-600' : selectedReport.severity === 'medium' ? 'text-amber-600' : 'text-green-600'}`}>Severity: {selectedReport.severity || 'low'}</p>
                      {selectedReport.assignedTeamId && (
                        <p className="text-sm font-bold text-blue-700 mt-1"><Users size={14} className="inline mr-1"/> Assigned: {fieldTeams.find(t => t.id === selectedReport.assignedTeamId)?.name || 'Field Unit'}</p>
                      )}
                    </div>
                  </div>
               </div>
               <div>
                  <h4 className="text-sm font-semibold text-gray-400 uppercase tracking-widest mb-1">Evidence / Photo</h4>
                  {selectedReport.photo_url ? (
                    <img src={selectedReport.photo_url} alt="Evidence" className="w-full h-64 md:h-full object-cover rounded-xl border border-gray-200 shadow-sm" />
                  ) : (
                    <div className="w-full h-64 md:h-full bg-gray-100 rounded-xl flex items-center justify-center border border-gray-200 text-gray-400 font-medium tracking-wide">No Image Uploaded</div>
                  )}
               </div>
            </div>
            <div className="p-4 border-t border-gray-100 bg-gray-50 flex justify-end space-x-3">
              <button 
                onClick={() => setSelectedReport(null)}
                className="px-6 py-2 bg-white border border-gray-300 text-gray-700 font-bold rounded-lg hover:bg-gray-50 active:scale-95 transition-transform"
              >
                Close Window
              </button>
            </div>
          </div>
        </div>
      )}
      </div>
    </div>
  );
}
